name: Run Docker Builds

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version: [mamba, micromamba, libmamba, miniconda]
        build_env: [pygrib, cartopy, geoips]
        
    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker compose build ${{ matrix.version }}_${{ matrix.build_env }} >> log
   
    - name: try to grep the output
      run: grep "DONE" log >>  ${{ matrix.version }}_${{ matrix.build_env }}.txt
    

    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v3.1.2
      with:
        path: "*.txt"
        
